Link do EDA do grupo 1
leobezerra/ds-zero pull request #3
Opened 2019-10-17 17:58 UTC by will-lucena

2019-10-19 10:28 UTC, leobezerra requested changes
Na parte de agrupar os dados dos jogadores, vocês não usaram os métodos disponíveis no DataFrame do Pandas.

Revisem isso e mandem de novo :)

2019-10-22 00:14 UTC, will-lucena reviewed
@leobezerra artigo atualizado, consegui fazer o agrupamento usando o groupby do pandas

2019-10-22 17:30 UTC, leobezerra approved these changes

2019-10-22 17:31 UTC, leobezerra approved these changes

2019-10-22 17:32 UTC, leobezerra approved these changes

2019-10-22 17:38 UTC, merged